{% set name = "pydda" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 639c5ee62756c1eeb9e22c18291705a8ea5a6989d770b28d0e6e819c6566127a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - xarray >=2024.10.0
    - numpy
    - scipy
    - matplotlib-base
    - cartopy
    - dask
    - distributed
    - six
    - arm_pyart

test:
  requires:
    - pytest
    - distributed
    - cfgrib
  imports:
    - pydda
  commands:
    - py.test --pyargs pydda

about:
  home: http://openradarscience.org/PyDDA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pythonic Direct Data Assimilation

  description: |
    PyDDA is a Pythonic package for developing wind retrievals.
    It uses the variational technique for assmilating together winds
    derived from radars and models.
  doc_url: http://openradarscience.org/PyDDA
  dev_url: https://github.com/openradar/PyDDA

extra:
  recipe-maintainers:
    - rcjackson
