provider:
   linux: travis
   osx: circle
   win: appveyor
travis:
  secure:
    BINSTAR_TOKEN: oS+WAcuI/LrboDR3WenAEDlY/x2m89yqXC4Laz86z306fbFquI+YsKO4/ESg/rcTGE7C5rHFaBJisY2qQxxDr3EWdYkgB/R/rEB2T3/U3q/WQ9gBhnhnQnOBSRTVvIhUnlbT+BGHpMDCFr65GRmFoOCFRdlma7C8MTQg7WC8Ft5D39N/NJdbV0jLa7EOD89iHyGMWV5bIJucmz6oUApX6llVUzFsjBvaVdlReC3wYJinFTAOOXiQ51ooF0x0+hhb+iRyX7FvoDG4FJEY4sr08NC8WQ4blhZfI32mB+WkWKj1Ga1+s7xQre90kzHSV+KwrNJmhIn2dXOgWoe0fOEtFZDsdJnf33+jc3EZyu808+3s3dEOAguMqWHhZGw3ponpvkZKf/2PWWwvj/a/PfINT7dwZg1CEV+Y1Flk15Pipx/OUKDofgDr4wXEHOIoQ0IG6ohZgb8KHn5UF76Wt3KjAafSq+Xvc+4scA67mAgsJ1kaZNxJVaddW4GHo+oG4j9KtgZbFL/mUd+ODuJoMg3OdlLtUcGmWT6sYEEt2zI9rTZn1jOhzG6CCDUEG9hlsaMHaWfTsoKdj+r3vBFIyrAH1EglydFsM08C4S65xZfafDhAVY0KoUA3QB7QzI/KPO+2R0uoliq9KYnzH2BkXGpQuDVHj9gsyaApHuOfWtbyKqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
